In [ ]:
import numpy as np
import pandas as pd

In [10]:
data=pd.read_excel(r'C:\Users\vodla\Downloads\Incois\Kerla_VNPillai_FishCatchData_final.xls')

In [11]:
data

,Fid,Exp No.,Type,SectorId,StationName,Pi_Id,Date_Of_Fishing,Time_Of_Departure,Arrival_Time,Duration_Total,...,Wind Direction,Sea Surface Temperature,OceanColour,PlanktonVolume,Chl_Concentration,Nitrate,Nitrite,Ammonia,Slicate,Phosphate
0,1,19,Pfz,5,Kollam,7,2008-03-04 00:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,19,Non-Pfz,5,Kollam,7,2008-03-04 00:00:00,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,20,Pfz,5,Edamuttom,7,2008-03-05 00:00:00,05:00:00,12:00:00,7hrs,...,Westerly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,20,Non-Pfz,5,Edamuttom,7,2008-03-05 00:00:00,05:00:00,10:00:00,5hrs,...,Westerly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,21,Pfz,5,Neendakara,7,2008-05-27 00:00:00,05:00:00,12:00:00,7hrs,...,W to NW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,162,97,Non-Pfz,5,Ramancheritura,7,2011-06-02 00:00:00,05:30:00,13:45:00,8hrs15min,...,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,163,98,Pfz,5,Edamuttom,7,2011-06-10 00:00:00,05:45:00,13:00:00,7hrs15min,...,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,164,98,Non-Pfz,5,Edamuttom,7,2011-06-10 00:00:00,05:30:00,13:30:00,8hrs,...,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,165,99,Pfz,5,Munambam,7,2011-06-15 00:00:00,05:30:00,12:30:00,7hrs,...,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,166,99,Non-Pfz,5,Munambam,7,2011-06-15 00:00:00,05:30:00,13:30:00,8-hrs,...,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.columns

Index(['Fid', 'Exp No.', 'Type', 'SectorId', 'StationName', 'Pi_Id',
       'Date_Of_Fishing', 'Time_Of_Departure', 'Arrival_Time',
       'Duration_Total', 'Name_Of_Vessel', 'Type_Of_Boat', 'Boat_Length',
       'Net_Type', 'pfzLatitude', 'pfzLongitude', 'pfzAngle', 'pfzDirection',
       'pfzDistance', 'pfzDepth', 'ValidityDate', 'Forcast_ReceivedOn',
       'Longitude', 'Latitude', 'Distance', 'Direction', 'Angle (Deg)',
       'Depth (m)', 'Fishing Hours', 'No of Hauls', 'No of Fishermen',
       'No of Boats', 'MajorSpecies_Caught', 'Unnamed: 33', 'Total_Catch',
       'Avg. Length', 'Staus_Of_Catch', 'Total_Expenditure', 'Fuel', 'wages',
       'Other_Expenses', 'Approximate cost', 'status of sea', 'status of sky',
       'Wind Direction', 'Sea Surface Temperature', 'OceanColour',
       'PlanktonVolume', 'Chl_Concentration', 'Nitrate', 'Nitrite', 'Ammonia',
       'Slicate', 'Phosphate'],
      dtype='object')

In [13]:
final=data[['Date_Of_Fishing','Latitude','Longitude','Total_Catch']].copy()

In [14]:
final

         Date_Of_Fishing   Latitude  Longitude  Total_Catch
0    2008-03-04 00:00:00   8.850000  76.466667       1700.0
1    2008-03-04 00:00:00   8.866667  76.516667        350.0
2    2008-03-05 00:00:00  10.250000  76.083333       4800.0
3    2008-03-05 00:00:00  10.166667  76.150000        700.0
4    2008-05-27 00:00:00   8.916667  76.500000       2100.0
..                   ...        ...        ...          ...
161  2011-06-02 00:00:00   9.166667  76.166667        210.0
162  2011-06-10 00:00:00  10.350000  75.833333       1200.0
163  2011-06-10 00:00:00  10.450000  75.833333        300.0
164  2011-06-15 00:00:00  10.333333  75.866667        950.0
165  2011-06-15 00:00:00  10.333333  75.866667        175.0

[166 rows x 4 columns]

In [15]:
final[final.duplicated()]

Empty DataFrame
Columns: [Date_Of_Fishing, Latitude, Longitude, Total_Catch]
Index: []

In [16]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date_Of_Fishing  166 non-null    object
 1   Latitude         162 non-null    float64
 2   Longitude        162 non-null    float64
 3   Total_Catch      163 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.3+ KB

In [17]:
final[final[['Latitude','Longitude']].isnull().any(axis=1)]

        Date_Of_Fishing  Latitude  Longitude  Total_Catch
48  2009-07-03 00:00:00       NaN        NaN       2500.0
49  2009-07-03 00:00:00       NaN        NaN        450.0
50  2009-07-13 00:00:00       NaN        NaN       1800.0
51  2009-07-13 00:00:00       NaN        NaN        200.0

In [18]:
final[final['Total_Catch'].isnull()]

        Date_Of_Fishing  Latitude  Longitude  Total_Catch
12  2008-10-05 00:00:00  9.333333  76.366667          NaN
13  2008-10-05 00:00:00  9.250000  76.333333          NaN
14  2008-10-05 00:00:00  9.150000  76.316667          NaN

In [19]:
final[final['Latitude'].isin([         9.25, 9.33305555556,          9.15,  15.330353615, 15.1233000086,
 14.7523605444, 15.0275681312,         17.37,         11.55,      13.13464,
      12.08344])]

         Date_Of_Fishing  Latitude  Longitude  Total_Catch
13   2008-10-05 00:00:00      9.25  76.333333          NaN
14   2008-10-05 00:00:00      9.15  76.316667          NaN
16   2008-10-05 00:00:00      9.25  76.333333        380.0
17   2008-10-05 00:00:00      9.25  76.350000        700.0
55   2009-08-26 00:00:00      9.15  76.283333        450.0
153  2011-05-12 00:00:00     11.55  75.416667        210.0

In [20]:
final[final.duplicated(subset=['Latitude','Longitude'], keep=False)]

         Date_Of_Fishing   Latitude  Longitude  Total_Catch
12   2008-10-05 00:00:00   9.333333  76.366667          NaN
13   2008-10-05 00:00:00   9.250000  76.333333          NaN
16   2008-10-05 00:00:00   9.250000  76.333333        380.0
27   2009-01-21 00:00:00   9.833333  76.166667        300.0
29   2009-01-24 00:00:00   9.833333  76.166667        250.0
34   2009-03-06 00:00:00   9.966667  76.133333       1100.0
35   2009-03-06 00:00:00   9.966667  76.133333        600.0
43   2009-05-19 00:00:00   9.966667  76.166667        950.0
48   2009-07-03 00:00:00        NaN        NaN       2500.0
49   2009-07-03 00:00:00        NaN        NaN        450.0
50   2009-07-13 00:00:00        NaN        NaN       1800.0
51   2009-07-13 00:00:00        NaN        NaN        200.0
74   2010-02-19 00:00:00   9.966667  76.166667       5000.0
86   2010-05-06 00:00:00  10.166667  76.333333       1400.0
91   2010-08-03 00:00:00  10.166667  76.333333        130.0
140  2011-03-09 00:00:00   9.333333  76.366667        900.0
164  2011-06-15 00:00:00  10.333333  75.866667        950.0
165  2011-06-15 00:00:00  10.333333  75.866667        175.0

In [21]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date_Of_Fishing  166 non-null    object
 1   Latitude         162 non-null    float64
 2   Longitude        162 non-null    float64
 3   Total_Catch      163 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.3+ KB

In [22]:
final

         Date_Of_Fishing   Latitude  Longitude  Total_Catch
0    2008-03-04 00:00:00   8.850000  76.466667       1700.0
1    2008-03-04 00:00:00   8.866667  76.516667        350.0
2    2008-03-05 00:00:00  10.250000  76.083333       4800.0
3    2008-03-05 00:00:00  10.166667  76.150000        700.0
4    2008-05-27 00:00:00   8.916667  76.500000       2100.0
..                   ...        ...        ...          ...
161  2011-06-02 00:00:00   9.166667  76.166667        210.0
162  2011-06-10 00:00:00  10.350000  75.833333       1200.0
163  2011-06-10 00:00:00  10.450000  75.833333        300.0
164  2011-06-15 00:00:00  10.333333  75.866667        950.0
165  2011-06-15 00:00:00  10.333333  75.866667        175.0

[166 rows x 4 columns]

In [23]:
final['Date_Of_Fishing']=pd.to_datetime(final['Date_Of_Fishing'], errors='coerce')

In [24]:
final

    Date_Of_Fishing   Latitude  Longitude  Total_Catch
0        2008-03-04   8.850000  76.466667       1700.0
1        2008-03-04   8.866667  76.516667        350.0
2        2008-03-05  10.250000  76.083333       4800.0
3        2008-03-05  10.166667  76.150000        700.0
4        2008-05-27   8.916667  76.500000       2100.0
..              ...        ...        ...          ...
161      2011-06-02   9.166667  76.166667        210.0
162      2011-06-10  10.350000  75.833333       1200.0
163      2011-06-10  10.450000  75.833333        300.0
164      2011-06-15  10.333333  75.866667        950.0
165      2011-06-15  10.333333  75.866667        175.0

[166 rows x 4 columns]

In [25]:
final[final['Total_Catch'].astype(str).str.contains(r'[a-zA-Z]', na=False, case=False)]

   Date_Of_Fishing  Latitude  Longitude  Total_Catch
12      2008-10-05  9.333333  76.366667          NaN
13      2008-10-05  9.250000  76.333333          NaN
14      2008-10-05  9.150000  76.316667          NaN

In [26]:
final.to_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_kerala.csv', index=False)