In [41]:
import pandas as pd
import numpy as np

In [42]:
Vis=pd.read_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_Vis.csv')
wb=pd.read_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_wb.csv')
kerala=pd.read_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_kerala.csv')
karn=pd.read_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_karn.csv')

In [43]:
Vis.info()
wb.info()
kerala.info()
karn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  242 non-null    int64
 1   Date        242 non-null    object
 2   Latitude    242 non-null    float64
 3   Longtitude  242 non-null    float64
 4   Total       234 non-null    float64
 5   Hook        238 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 11.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         152 non-null    object
 1   Latitude     152 non-null    float64
 2   Longitude    152 non-null    float64
 3   Total Catch  152 non-null    int64
dtypes: float64(2), int64(1), object(1)
memory usage: 4.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date_Of_Fishing  166 non-null    object
 1   Latitude         162 non-null    float64
 2   Longitude        162 non-null    float64
 3   Total_Catch      163 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    10 non-null     object
 1   Total   10 non-null     float64
 2   Lat     10 non-null     float64
 3   Long    10 non-null     float64
dtypes: float64(3), object(1)
memory usage: 452.0+ bytes

In [44]:
Vis

     Unnamed: 0                 Date   Latitude  Longtitude  Total   Hook
0           239  2014-05-01 05:00:00  20.633333   88.200000    3.0  100.0
1             3  2010-01-20 03:00:00  17.050000   83.216667    7.0  300.0
2           179  2012-11-22 04:00:00  20.066667   81.416667   18.0  300.0
3           178  2012-11-21 04:00:00  20.033333   81.416667    3.0  300.0
4           167  2012-11-16 01:00:00  19.416667   83.633333   18.0  300.0
..          ...                  ...        ...         ...    ...    ...
237         136  2012-06-08 04:00:00  17.550000   83.883333  123.0  800.0
238         201  2013-07-26 04:00:00  17.050000   83.566667    NaN    NaN
239         202  2013-07-27 04:00:00  17.050000   83.566667    NaN    NaN
240         203  2013-07-28 04:00:00  17.050000   83.566667    NaN    NaN
241         204  2013-07-29 04:00:00  17.050000   83.566667    NaN    NaN

[242 rows x 6 columns]

In [45]:
Vis.drop(columns=['Unnamed: 0'], inplace=True)

In [46]:
wb

           Date  Latitude  Longitude  Total Catch
0    2013-06-29   21.3276    88.3442           85
1    2013-01-07   21.2924    88.2591           90
2    2013-01-07   21.2876    88.2927          100
3    2013-02-07   21.3542    88.2076           50
4    2013-02-07   21.2837    88.2924           50
..          ...       ...        ...          ...
147  2014-12-02   21.0841    88.0840           68
148  2014-02-13   21.0509    88.0842          225
149  2014-02-14   21.1170    88.0504          435
150  2014-02-15   21.0502    88.2505           25
151  2014-02-16   21.0005    88.3675           30

[152 rows x 4 columns]

In [47]:
kerala

    Date_Of_Fishing   Latitude  Longitude  Total_Catch
0        2008-03-04   8.850000  76.466667       1700.0
1        2008-03-04   8.866667  76.516667        350.0
2        2008-03-05  10.250000  76.083333       4800.0
3        2008-03-05  10.166667  76.150000        700.0
4        2008-05-27   8.916667  76.500000       2100.0
..              ...        ...        ...          ...
161      2011-06-02   9.166667  76.166667        210.0
162      2011-06-10  10.350000  75.833333       1200.0
163      2011-06-10  10.450000  75.833333        300.0
164      2011-06-15  10.333333  75.866667        950.0
165      2011-06-15  10.333333  75.866667        175.0

[166 rows x 4 columns]

In [48]:
karn

         Date   Total        Lat       Long
0  2014-10-01   79.65  13.262250  74.476092
1  2014-10-01  213.59  13.305425  74.458825
2  2014-01-23  413.95  12.858325  74.727392
3  2014-01-23   99.50  12.835642  74.679308
4  2014-01-27  186.10  13.398150  74.588683
5  2014-01-27  282.80  13.391500  74.579500
6  2014-02-07  265.95  12.858325  74.727392
7  2014-02-07  157.10  12.835642  74.679308
8  2014-02-20  243.35  13.398150  74.588683
9  2014-02-20  432.80  13.391500  74.579500

In [49]:
karn=karn[['Date','Lat','Long','Total']]

In [50]:

Vis.columns=['Date','Latitude','Longtitude','Total','Hook']
wb.columns=['Date','Latitude','Longtitude','Total']
kerala.columns=['Date','Latitude','Longtitude','Total']
karn.columns=['Date','Latitude','Longtitude','Total']

In [51]:
Vis.info()
wb.info()
kerala.info()
karn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        242 non-null    object
 1   Latitude    242 non-null    float64
 2   Longtitude  242 non-null    float64
 3   Total       234 non-null    float64
 4   Hook        238 non-null    float64
dtypes: float64(4), object(1)
memory usage: 9.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        152 non-null    object
 1   Latitude    152 non-null    float64
 2   Longtitude  152 non-null    float64
 3   Total       152 non-null    int64
dtypes: float64(2), int64(1), object(1)
memory usage: 4.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        166 non-null    object
 1   Latitude    162 non-null    float64
 2   Longtitude  162 non-null    float64
 3   Total       163 non-null    float64
dtypes: float64(3), object(1)
memory usage: 5.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Latitude    10 non-null     float64
 2   Longtitude  10 non-null     float64
 3   Total       10 non-null     float64
dtypes: float64(3), object(1)
memory usage: 452.0+ bytes

In [52]:
master=pd.concat([Vis,wb,kerala,karn])

In [53]:
master

                   Date   Latitude  Longtitude   Total   Hook
0   2014-05-01 05:00:00  20.633333   88.200000    3.00  100.0
1   2010-01-20 03:00:00  17.050000   83.216667    7.00  300.0
2   2012-11-22 04:00:00  20.066667   81.416667   18.00  300.0
3   2012-11-21 04:00:00  20.033333   81.416667    3.00  300.0
4   2012-11-16 01:00:00  19.416667   83.633333   18.00  300.0
..                  ...        ...         ...     ...    ...
5            2014-01-27  13.391500   74.579500  282.80    NaN
6            2014-02-07  12.858325   74.727392  265.95    NaN
7            2014-02-07  12.835642   74.679308  157.10    NaN
8            2014-02-20  13.398150   74.588683  243.35    NaN
9            2014-02-20  13.391500   74.579500  432.80    NaN

[570 rows x 5 columns]

In [54]:
master['Date']=pd.to_datetime(master['Date'],errors='coerce',format='mixed')

In [55]:
master.drop_duplicates(keep='first',inplace=True)

In [56]:
master=master[~(master.duplicated(subset=['Date','Latitude','Longtitude'],keep=False) & master['Total'].isna())]

In [57]:
master.sort_values(['Date','Latitude','Longtitude'])

                   Date   Latitude  Longtitude   Total   Hook
106 1900-01-05 00:00:00   9.633333   76.433333  1150.0    NaN
7   1931-04-07 00:00:00  21.257600   88.256900    30.0    NaN
0   2008-03-04 00:00:00   8.850000   76.466667  1700.0    NaN
1   2008-03-04 00:00:00   8.866667   76.516667   350.0    NaN
3   2008-03-05 00:00:00  10.166667   76.150000   700.0    NaN
..                  ...        ...         ...     ...    ...
128 2014-11-01 00:00:00  21.100500   88.267200    15.0    NaN
146 2014-11-02 00:00:00  21.100400   88.266900   358.0    NaN
129 2014-12-01 00:00:00  20.916900   88.350400    10.0    NaN
37  2014-12-01 05:00:00  19.283333   85.900000     6.0  300.0
147 2014-12-02 00:00:00  21.084100   88.084000    68.0    NaN

[569 rows x 5 columns]

In [58]:
master=master[~((master['Latitude']==0) | (master['Longtitude']==0))]

In [59]:
master.dropna(subset=['Latitude','Longtitude'],inplace=True)

In [60]:
master.info()

<class 'pandas.core.frame.DataFrame'>
Index: 565 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        565 non-null    datetime64[ns]
 1   Latitude    565 non-null    float64
 2   Longtitude  565 non-null    float64
 3   Total       555 non-null    float64
 4   Hook        238 non-null    float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 26.5 KB

In [61]:
print(master.isna().sum())

Date            0
Latitude        0
Longtitude      0
Total          10
Hook          327
dtype: int64

In [62]:
print(master.describe())

                                Date    Latitude  Longtitude        Total  \
count                            565  565.000000  565.000000   555.000000
mean   2011-12-13 00:33:27.079645952   16.912983   83.127200   347.567189
min              1900-01-05 00:00:00    8.666667   17.633333     0.000000
25%              2011-01-24 00:00:00   11.366667   76.333333    10.000000
50%              2012-08-29 04:00:00   19.366667   85.683333    35.000000
75%              2013-09-09 00:00:00   20.917200   88.183900   272.500000
max              2014-12-02 00:00:00   21.583700   89.290100  8000.000000
std                              NaN    4.543904    6.420854   777.308332

             Hook
count  238.000000
mean   408.907563
min    100.000000
25%    350.000000
50%    400.000000
75%    400.000000
max    800.000000
std     95.848773

In [63]:
master.to_csv(r'C:\Users\vodla\Downloads\Incois\data_renew.csv',index=False)