In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.ExcelFile(r'C:\Users\vodla\Downloads\Incois\08-Visakhapatnam_USreedhar_Data_2013-14.xlsx')

In [ ]:
data.sheet_names

['catch data ', 'Voyage details']

In [5]:
catch=data.parse('catch data ')

In [6]:
catch

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,MONTH WISE HOOKING RATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,vessel Name,Bait,Voyage Period,Date,Time,Lat,Long,Total Catch,No. of Hook,YFT,SKJ,BET,MARLIN,SWO,SHK
2,NaN,NaN,2010-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAI PRIYA,mackrel,18.01.10-08.02.10,20.1.10,3.00AM,17.03,83.13,7,300,7,0,0,0,0,0
4,SAI PRIYA,mackrel,18.01.10-08.02.10,22.1.10,3.00AM,17.57,83.21,8,300,8,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,saiprasanna,mackrel,10.1.14-3-2-14,27.1.14,5.00AM,20.37,88.13,3,300,NaN,NaN,NaN,3,NaN,NaN
263,saiprasanna,mackrel,10.1.14-3-2-14,30.1.14,5.00AM,19.37,86.28,12,300,7,NaN,NaN,5,NaN,NaN
264,saiprasanna,mackrel,10.1.14-3-2-14,31.01.14,5.00AM,19.35,86.29,17,300,8,NaN,NaN,8,NaN,1
265,NaN,NaN,2014-02-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,saiprasanna,mackrel,10.1.14-3-2-14,2.2.14,5.00AM,19.26,86.07,11,300,3,NaN,NaN,8,NaN,NaN

In [7]:
catch.columns=catch.iloc[1]
catch=catch.iloc[2:,:]

In [8]:
catch

1,vessel Name,Bait,Voyage Period,Date,Time,Lat,Long,Total Catch,No. of Hook,YFT,SKJ,BET,MARLIN,SWO,SHK
2,NaN,NaN,2010-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAI PRIYA,mackrel,18.01.10-08.02.10,20.1.10,3.00AM,17.03,83.13,7,300,7,0,0,0,0,0
4,SAI PRIYA,mackrel,18.01.10-08.02.10,22.1.10,3.00AM,17.57,83.21,8,300,8,NaN,NaN,NaN,NaN,NaN
5,SAI PRIYA,mackrel,18.01.10-08.02.10,23.1.10,3.00AM,17.07,83.13,7,300,7,NaN,NaN,NaN,NaN,NaN
6,SAI PRIYA,mackrel,18.01.10-08.02.10,24.1.10,3.00AM,17.18,83.38,4,300,4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,saiprasanna,mackrel,10.1.14-3-2-14,27.1.14,5.00AM,20.37,88.13,3,300,NaN,NaN,NaN,3,NaN,NaN
263,saiprasanna,mackrel,10.1.14-3-2-14,30.1.14,5.00AM,19.37,86.28,12,300,7,NaN,NaN,5,NaN,NaN
264,saiprasanna,mackrel,10.1.14-3-2-14,31.01.14,5.00AM,19.35,86.29,17,300,8,NaN,NaN,8,NaN,1
265,NaN,NaN,2014-02-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,saiprasanna,mackrel,10.1.14-3-2-14,2.2.14,5.00AM,19.26,86.07,11,300,3,NaN,NaN,8,NaN,NaN

In [9]:
catch=catch[['Date','Time','Lat','Long','Total Catch','No. of Hook']]

In [10]:
catch

1        Date    Time    Lat   Long Total Catch No. of Hook
2         NaN     NaN    NaN    NaN         NaN         NaN
3     20.1.10  3.00AM  17.03  83.13           7         300
4     22.1.10  3.00AM  17.57  83.21           8         300
5     23.1.10  3.00AM  17.07  83.13           7         300
6     24.1.10  3.00AM  17.18  83.38           4         300
..        ...     ...    ...    ...         ...         ...
262   27.1.14  5.00AM  20.37  88.13           3         300
263   30.1.14  5.00AM  19.37  86.28          12         300
264  31.01.14  5.00AM  19.35  86.29          17         300
265       NaN     NaN    NaN    NaN         NaN         NaN
266    2.2.14  5.00AM  19.26  86.07          11         300

[265 rows x 6 columns]

In [11]:
catch[catch['Lat']==20]

1        Date    Time Lat   Long Total Catch No. of Hook
165  14.11.12  1.00AM  20  87.05          14         300

In [12]:
catch.dropna(how='all',inplace=True)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\3471002953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch.dropna(how='all',inplace=True)

In [13]:
catch[catch.duplicated(subset=['Date','Time','Lat','Long','Total Catch','No. of Hook'],keep=False)]

Empty DataFrame
Columns: [Date, Time, Lat, Long, Total Catch, No. of Hook]
Index: []

In [14]:
catch

1        Date    Time    Lat   Long Total Catch No. of Hook
3     20.1.10  3.00AM  17.03  83.13           7         300
4     22.1.10  3.00AM  17.57  83.21           8         300
5     23.1.10  3.00AM  17.07  83.13           7         300
6     24.1.10  3.00AM  17.18  83.38           4         300
7     25.1.10  3.00AM   17.1  83.44          10         300
..        ...     ...    ...    ...         ...         ...
261   26.1.14  5.00AM   20.4  88.18           3         300
262   27.1.14  5.00AM  20.37  88.13           3         300
263   30.1.14  5.00AM  19.37  86.28          12         300
264  31.01.14  5.00AM  19.35  86.29          17         300
266    2.2.14  5.00AM  19.26  86.07          11         300

[245 rows x 6 columns]

In [15]:
catch['Time']=catch['Time'].astype(str).str.replace('AM','.00' ,case=False)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2483284735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Time']=catch['Time'].astype(str).str.replace('AM','.00' ,case=False)

In [16]:
catch

1        Date     Time    Lat   Long Total Catch No. of Hook
3     20.1.10  3.00.00  17.03  83.13           7         300
4     22.1.10  3.00.00  17.57  83.21           8         300
5     23.1.10  3.00.00  17.07  83.13           7         300
6     24.1.10  3.00.00  17.18  83.38           4         300
7     25.1.10  3.00.00   17.1  83.44          10         300
..        ...      ...    ...    ...         ...         ...
261   26.1.14  5.00.00   20.4  88.18           3         300
262   27.1.14  5.00.00  20.37  88.13           3         300
263   30.1.14  5.00.00  19.37  86.28          12         300
264  31.01.14  5.00.00  19.35  86.29          17         300
266    2.2.14  5.00.00  19.26  86.07          11         300

[245 rows x 6 columns]

In [17]:
catch['Time']=catch['Time'].astype(str).str.replace('.',':' ,case=False)
catch['Date']=catch['Date'].astype(str).str.replace('.','-' ,case=False)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2468288722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Time']=catch['Time'].astype(str).str.replace('.',':' ,case=False)
C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2468288722.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Date']=catch['Date'].astype(str).str.replace('.','-' ,case=False)

In [18]:
catch

1        Date     Time    Lat   Long Total Catch No. of Hook
3     20-1-10  3:00:00  17.03  83.13           7         300
4     22-1-10  3:00:00  17.57  83.21           8         300
5     23-1-10  3:00:00  17.07  83.13           7         300
6     24-1-10  3:00:00  17.18  83.38           4         300
7     25-1-10  3:00:00   17.1  83.44          10         300
..        ...      ...    ...    ...         ...         ...
261   26-1-14  5:00:00   20.4  88.18           3         300
262   27-1-14  5:00:00  20.37  88.13           3         300
263   30-1-14  5:00:00  19.37  86.28          12         300
264  31-01-14  5:00:00  19.35  86.29          17         300
266    2-2-14  5:00:00  19.26  86.07          11         300

[245 rows x 6 columns]

In [19]:
catch['Date']=catch['Date'] +' '+catch['Time']

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2239019724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Date']=catch['Date'] +' '+catch['Time']

In [20]:
catch

1                Date     Time    Lat   Long Total Catch No. of Hook
3     20-1-10 3:00:00  3:00:00  17.03  83.13           7         300
4     22-1-10 3:00:00  3:00:00  17.57  83.21           8         300
5     23-1-10 3:00:00  3:00:00  17.07  83.13           7         300
6     24-1-10 3:00:00  3:00:00  17.18  83.38           4         300
7     25-1-10 3:00:00  3:00:00   17.1  83.44          10         300
..                ...      ...    ...    ...         ...         ...
261   26-1-14 5:00:00  5:00:00   20.4  88.18           3         300
262   27-1-14 5:00:00  5:00:00  20.37  88.13           3         300
263   30-1-14 5:00:00  5:00:00  19.37  86.28          12         300
264  31-01-14 5:00:00  5:00:00  19.35  86.29          17         300
266    2-2-14 5:00:00  5:00:00  19.26  86.07          11         300

[245 rows x 6 columns]

In [21]:
catch[catch['Lat']==19.27]

1                 Date     Time    Lat   Long Total Catch No. of Hook
21  24-11-2011 4:00:00  4:00:00  19.27  85.56           8         400
22  25-11-2011 4:00:00  4:00:00  19.27  85.53           4         400
24   27-11-011 4:00:00  4:00:00  19.27  85.56          10         400
43  23-12-2011 4:00:00  4:00:00  19.27  85.56           1         400

In [22]:
catch['Date'] = catch['Date'].str.replace(r'-(\d{3})\s',r'-2\1 ',regex=True)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\158177186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Date'] = catch['Date'].str.replace(r'-(\d{3})\s',r'-2\1 ',regex=True)

In [23]:
catch.drop(columns='Time',inplace=True)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\918461437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch.drop(columns='Time',inplace=True)

In [24]:
catch

1                Date    Lat   Long Total Catch No. of Hook
3     20-1-10 3:00:00  17.03  83.13           7         300
4     22-1-10 3:00:00  17.57  83.21           8         300
5     23-1-10 3:00:00  17.07  83.13           7         300
6     24-1-10 3:00:00  17.18  83.38           4         300
7     25-1-10 3:00:00   17.1  83.44          10         300
..                ...    ...    ...         ...         ...
261   26-1-14 5:00:00   20.4  88.18           3         300
262   27-1-14 5:00:00  20.37  88.13           3         300
263   30-1-14 5:00:00  19.37  86.28          12         300
264  31-01-14 5:00:00  19.35  86.29          17         300
266    2-2-14 5:00:00  19.26  86.07          11         300

[245 rows x 5 columns]

In [25]:
catch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 245 entries, 3 to 266
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         245 non-null    object
 1   Lat          245 non-null    object
 2   Long         244 non-null    object
 3   Total Catch  241 non-null    object
 4   No. of Hook  245 non-null    object
dtypes: object(5)
memory usage: 11.5+ KB

In [26]:
df=catch.copy()

In [27]:
catch['Date']=pd.to_datetime(catch['Date'],errors='coerce')

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2046488300.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  catch['Date']=pd.to_datetime(catch['Date'],errors='coerce')
C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2046488300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Date']=pd.to_datetime(catch['Date'],errors='coerce')

In [28]:
catch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 245 entries, 3 to 266
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         245 non-null    datetime64[ns]
 1   Lat          245 non-null    object
 2   Long         244 non-null    object
 3   Total Catch  241 non-null    object
 4   No. of Hook  245 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 11.5+ KB

In [29]:
df[catch['Date'].isnull()]

Empty DataFrame
Columns: [Date, Lat, Long, Total Catch, No. of Hook]
Index: []

In [30]:
catch

1                  Date    Lat   Long Total Catch No. of Hook
3   2010-01-20 03:00:00  17.03  83.13           7         300
4   2010-01-22 03:00:00  17.57  83.21           8         300
5   2010-01-23 03:00:00  17.07  83.13           7         300
6   2010-01-24 03:00:00  17.18  83.38           4         300
7   2010-01-25 03:00:00   17.1  83.44          10         300
..                  ...    ...    ...         ...         ...
261 2014-01-26 05:00:00   20.4  88.18           3         300
262 2014-01-27 05:00:00  20.37  88.13           3         300
263 2014-01-30 05:00:00  19.37  86.28          12         300
264 2014-01-31 05:00:00  19.35  86.29          17         300
266 2014-02-02 05:00:00  19.26  86.07          11         300

[245 rows x 5 columns]

In [31]:
catch = catch[~catch['Lat'].astype(str).str.contains('[a-zA-Z]', na=False)]

In [32]:
import convert

In [33]:
catch['Lat'] = catch['Lat'].astype(str).str.replace('.', ' ', regex=False)
catch['Long'] = catch['Long'].astype(str).str.replace('.', ' ', regex=False)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2293085054.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Lat'] = catch['Lat'].astype(str).str.replace('.', ' ', regex=False)
C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2293085054.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Long'] = catch['Long'].astype(str).str.replace('.', ' ', regex=False)

In [34]:
catch

1                  Date    Lat   Long Total Catch No. of Hook
3   2010-01-20 03:00:00  17 03  83 13           7         300
4   2010-01-22 03:00:00  17 57  83 21           8         300
5   2010-01-23 03:00:00  17 07  83 13           7         300
6   2010-01-24 03:00:00  17 18  83 38           4         300
7   2010-01-25 03:00:00   17 1  83 44          10         300
..                  ...    ...    ...         ...         ...
261 2014-01-26 05:00:00   20 4  88 18           3         300
262 2014-01-27 05:00:00  20 37  88 13           3         300
263 2014-01-30 05:00:00  19 37  86 28          12         300
264 2014-01-31 05:00:00  19 35  86 29          17         300
266 2014-02-02 05:00:00  19 26  86 07          11         300

[242 rows x 5 columns]

In [35]:
import convert
import importlib
importlib.reload(convert)

In [36]:
catch['Lat'] = catch['Lat'].apply(convert.convert_coord)
catch['Long'] = catch['Long'].apply(convert.convert_coord)

catch

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\1035110013.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Lat'] = catch['Lat'].apply(convert.convert_coord)
C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\1035110013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Long'] = catch['Long'].apply(convert.convert_coord)

1                  Date        Lat       Long Total Catch No. of Hook
3   2010-01-20 03:00:00  17.050000  83.216667           7         300
4   2010-01-22 03:00:00  17.950000  83.350000           8         300
5   2010-01-23 03:00:00  17.116667  83.216667           7         300
6   2010-01-24 03:00:00  17.300000  83.633333           4         300
7   2010-01-25 03:00:00  17.016667  83.733333          10         300
..                  ...        ...        ...         ...         ...
261 2014-01-26 05:00:00  20.066667  88.300000           3         300
262 2014-01-27 05:00:00  20.616667  88.216667           3         300
263 2014-01-30 05:00:00  19.616667  86.466667          12         300
264 2014-01-31 05:00:00  19.583333  86.483333          17         300
266 2014-02-02 05:00:00  19.433333  86.116667          11         300

[242 rows x 5 columns]

In [37]:
catch[catch['Total Catch'].astype(str).str.contains(' ')]

Empty DataFrame
Columns: [Date, Lat, Long, Total Catch, No. of Hook]
Index: []

In [38]:
catch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 242 entries, 3 to 266
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         242 non-null    datetime64[ns]
 1   Lat          242 non-null    float64
 2   Long         242 non-null    float64
 3   Total Catch  238 non-null    object
 4   No. of Hook  242 non-null    object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 11.3+ KB

In [39]:
catch['Total Catch']=pd.to_numeric(catch['Total Catch'],errors='coerce')
catch['No. of Hook']=pd.to_numeric(catch['No. of Hook'],errors='coerce')

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2338134576.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['Total Catch']=pd.to_numeric(catch['Total Catch'],errors='coerce')
C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\2338134576.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch['No. of Hook']=pd.to_numeric(catch['No. of Hook'],errors='coerce')

In [40]:
catch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 242 entries, 3 to 266
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         242 non-null    datetime64[ns]
 1   Lat          242 non-null    float64
 2   Long         242 non-null    float64
 3   Total Catch  234 non-null    float64
 4   No. of Hook  238 non-null    float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 11.3 KB

In [41]:
catch.sort_values(by=['No. of Hook'], inplace=True)

C:\Users\vodla\AppData\Local\Temp\ipykernel_19488\3700038194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  catch.sort_values(by=['No. of Hook'], inplace=True)

In [42]:
catch

1                  Date        Lat       Long  Total Catch  No. of Hook
239 2014-05-01 05:00:00  20.633333  88.200000          3.0        100.0
3   2010-01-20 03:00:00  17.050000  83.216667          7.0        300.0
179 2012-11-22 04:00:00  20.066667  81.416667         18.0        300.0
178 2012-11-21 04:00:00  20.033333  81.416667          3.0        300.0
167 2012-11-16 01:00:00  19.416667  83.633333         18.0        300.0
..                  ...        ...        ...          ...          ...
136 2012-06-08 04:00:00  17.550000  83.883333        123.0        800.0
201 2013-07-26 04:00:00  17.050000  83.566667          NaN          NaN
202 2013-07-27 04:00:00  17.050000  83.566667          NaN          NaN
203 2013-07-28 04:00:00  17.050000  83.566667          NaN          NaN
204 2013-07-29 04:00:00  17.050000  83.566667          NaN          NaN

[242 rows x 5 columns]

In [43]:
catch.columns=['Date','Latitude','Longtitude','Total','Hook']

In [44]:
catch.to_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_Vis.csv')