In [ ]:
import numpy as np
import pandas as pd

In [132]:
data=pd.ExcelFile(r'C:\Users\vodla\Downloads\Incois\03-Karnataka_Benakappa_Data_2013-14.xlsx')

In [133]:
data.sheet_names

['Information of station',
 'Physico-chem para of water',
 'Plankton',
 'Fish catch',
 'reproductive biology',
 'Food and feeding habits']

In [134]:
catch=data.parse('Fish catch')

In [135]:
catch.dropna(how='all',inplace=True)

In [136]:
catch.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [137]:
catch

,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
3,NaN,Fish catch composition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Station,Date,Latitude,Langitude,Latitude,Langitude,Saurida tumbil,Anodontostoma chacunda,Sardinella gibbosa,Sardinella longiceps,...,Netuma thalassina,Lagocephalus inermis,Loligo duvauceli,Octopus vulgaris,Sepia inermis,Portunidae,Calappa calappa,Penaeidae,Discards,Total
8,NaN,NaN,Starting Point,NaN,End Point,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PFZ,2014-10-01 00:00:00,13o 15' 235'' N,74o 28' 608'' E,13o 16' 235'' N,74o 28' 523'' E,0.2,0,0.1,0,...,0,0,0.3,0.1,0.2,0.2,0.4,0,72.8,79.65
10,Non PFZ,NaN,13o 17' 547'' N,74o 27' 638'' E,13o 19' 104'' N,74o 27' 421'' E,2,0,0.5,0,...,0,2,0.3,0.1,0.2,0.6,1,0,192.54,213.59
11,20mt (S1 & S2),23/01/2014,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,0.2,0.1,0.2,1.5,...,0.15,1.5,0.5,0.1,0.1,10,2,3,380.7,413.95
12,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,0.5,0,0.5,0,...,0,3.5,3,0,0.1,3,2,4,70.2,99.5
13,20mt (S5 & S6),27/01/2014,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,0,0.1,0,0.5,...,0,0,0.5,0.1,0.1,6,2,3,158.2,186.1
14,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,2,0,0.2,2,...,0.1,2,2,0,0.2,3,4,6,243.8,282.8
15,20mt (S1 & S2),2014-02-07 00:00:00,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,2.5,0,0,0.5,...,0.2,2,2,0,0,5,1,2,240.1,265.95
16,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,2.2,0,0.1,0,...,0,0.5,3,0.2,0.2,4,0.5,4,125.8,157.1
17,20mt (S5 & S6),2014-02-20 00:00:00,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,1,0,0,0,...,0,0,1,0,0,5,8,7,198.6,243.35
18,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,1.5,0,0,0,...,0,5,2,0,0.1,3,5,1.5,402.1,432.8

In [138]:
catch.dropna(subset=['Unnamed: 5'],inplace=True)

In [139]:
catch

,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
7,Station,Date,Latitude,Langitude,Latitude,Langitude,Saurida tumbil,Anodontostoma chacunda,Sardinella gibbosa,Sardinella longiceps,...,Netuma thalassina,Lagocephalus inermis,Loligo duvauceli,Octopus vulgaris,Sepia inermis,Portunidae,Calappa calappa,Penaeidae,Discards,Total
9,PFZ,2014-10-01 00:00:00,13o 15' 235'' N,74o 28' 608'' E,13o 16' 235'' N,74o 28' 523'' E,0.2,0,0.1,0,...,0,0,0.3,0.1,0.2,0.2,0.4,0,72.8,79.65
10,Non PFZ,NaN,13o 17' 547'' N,74o 27' 638'' E,13o 19' 104'' N,74o 27' 421'' E,2,0,0.5,0,...,0,2,0.3,0.1,0.2,0.6,1,0,192.54,213.59
11,20mt (S1 & S2),23/01/2014,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,0.2,0.1,0.2,1.5,...,0.15,1.5,0.5,0.1,0.1,10,2,3,380.7,413.95
12,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,0.5,0,0.5,0,...,0,3.5,3,0,0.1,3,2,4,70.2,99.5
13,20mt (S5 & S6),27/01/2014,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,0,0.1,0,0.5,...,0,0,0.5,0.1,0.1,6,2,3,158.2,186.1
14,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,2,0,0.2,2,...,0.1,2,2,0,0.2,3,4,6,243.8,282.8
15,20mt (S1 & S2),2014-02-07 00:00:00,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,2.5,0,0,0.5,...,0.2,2,2,0,0,5,1,2,240.1,265.95
16,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,2.2,0,0.1,0,...,0,0.5,3,0.2,0.2,4,0.5,4,125.8,157.1
17,20mt (S5 & S6),2014-02-20 00:00:00,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,1,0,0,0,...,0,0,1,0,0,5,8,7,198.6,243.35
18,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,1.5,0,0,0,...,0,5,2,0,0.1,3,5,1.5,402.1,432.8

In [140]:
catch.columns=catch.iloc[0]
catch=catch[1:]

In [141]:
catch

7,Station,Date,Latitude,Langitude,Latitude,Langitude,Saurida tumbil,Anodontostoma chacunda,Sardinella gibbosa,Sardinella longiceps,...,Netuma thalassina,Lagocephalus inermis,Loligo duvauceli,Octopus vulgaris,Sepia inermis,Portunidae,Calappa calappa,Penaeidae,Discards,Total
9,PFZ,2014-10-01 00:00:00,13o 15' 235'' N,74o 28' 608'' E,13o 16' 235'' N,74o 28' 523'' E,0.2,0,0.1,0,...,0,0,0.3,0.1,0.2,0.2,0.4,0,72.8,79.65
10,Non PFZ,NaN,13o 17' 547'' N,74o 27' 638'' E,13o 19' 104'' N,74o 27' 421'' E,2,0,0.5,0,...,0,2,0.3,0.1,0.2,0.6,1,0,192.54,213.59
11,20mt (S1 & S2),23/01/2014,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,0.2,0.1,0.2,1.5,...,0.15,1.5,0.5,0.1,0.1,10,2,3,380.7,413.95
12,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,0.5,0,0.5,0,...,0,3.5,3,0,0.1,3,2,4,70.2,99.5
13,20mt (S5 & S6),27/01/2014,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,0,0.1,0,0.5,...,0,0,0.5,0.1,0.1,6,2,3,158.2,186.1
14,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,2,0,0.2,2,...,0.1,2,2,0,0.2,3,4,6,243.8,282.8
15,20mt (S1 & S2),2014-02-07 00:00:00,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,2.5,0,0,0.5,...,0.2,2,2,0,0,5,1,2,240.1,265.95
16,30mt (S3 & S4),NaN,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,2.2,0,0.1,0,...,0,0.5,3,0.2,0.2,4,0.5,4,125.8,157.1
17,20mt (S5 & S6),2014-02-20 00:00:00,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,1,0,0,0,...,0,0,1,0,0,5,8,7,198.6,243.35
18,30mt (S7 & S8),NaN,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,1.5,0,0,0,...,0,5,2,0,0.1,3,5,1.5,402.1,432.8

In [142]:
catch['Date']=catch['Date'].ffill()

In [143]:
cols = list(catch.columns)

cols[2] = 'Lat_start'
cols[3] = 'Long_start'
cols[4] = 'Lat_end'
cols[5] = 'Long_end'

catch.columns = cols

In [144]:
catch

,Station,Date,Lat_start,Long_start,Lat_end,Long_end,Saurida tumbil,Anodontostoma chacunda,Sardinella gibbosa,Sardinella longiceps,...,Netuma thalassina,Lagocephalus inermis,Loligo duvauceli,Octopus vulgaris,Sepia inermis,Portunidae,Calappa calappa,Penaeidae,Discards,Total
9,PFZ,2014-10-01 00:00:00,13o 15' 235'' N,74o 28' 608'' E,13o 16' 235'' N,74o 28' 523'' E,0.2,0,0.1,0,...,0,0,0.3,0.1,0.2,0.2,0.4,0,72.8,79.65
10,Non PFZ,2014-10-01 00:00:00,13o 17' 547'' N,74o 27' 638'' E,13o 19' 104'' N,74o 27' 421'' E,2,0,0.5,0,...,0,2,0.3,0.1,0.2,0.6,1,0,192.54,213.59
11,20mt (S1 & S2),23/01/2014,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,0.2,0.1,0.2,1.5,...,0.15,1.5,0.5,0.1,0.1,10,2,3,380.7,413.95
12,30mt (S3 & S4),23/01/2014,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,0.5,0,0.5,0,...,0,3.5,3,0,0.1,3,2,4,70.2,99.5
13,20mt (S5 & S6),27/01/2014,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,0,0.1,0,0.5,...,0,0,0.5,0.1,0.1,6,2,3,158.2,186.1
14,30mt (S7 & S8),27/01/2014,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,2,0,0.2,2,...,0.1,2,2,0,0.2,3,4,6,243.8,282.8
15,20mt (S1 & S2),2014-02-07 00:00:00,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,2.5,0,0,0.5,...,0.2,2,2,0,0,5,1,2,240.1,265.95
16,30mt (S3 & S4),2014-02-07 00:00:00,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,2.2,0,0.1,0,...,0,0.5,3,0.2,0.2,4,0.5,4,125.8,157.1
17,20mt (S5 & S6),2014-02-20 00:00:00,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,1,0,0,0,...,0,0,1,0,0,5,8,7,198.6,243.35
18,30mt (S7 & S8),2014-02-20 00:00:00,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,1.5,0,0,0,...,0,5,2,0,0.1,3,5,1.5,402.1,432.8

In [145]:
catch=catch[['Date','Lat_start','Long_start','Lat_end','Long_end','Total']]

In [146]:
catch

,Date,Lat_start,Long_start,Lat_end,Long_end,Total
9,2014-10-01 00:00:00,13o 15' 235'' N,74o 28' 608'' E,13o 16' 235'' N,74o 28' 523'' E,79.65
10,2014-10-01 00:00:00,13o 17' 547'' N,74o 27' 638'' E,13o 19' 104'' N,74o 27' 421'' E,213.59
11,23/01/2014,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,413.95
12,23/01/2014,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,99.5
13,27/01/2014,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,186.1
14,27/01/2014,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,282.8
15,2014-02-07 00:00:00,12o 51' 571'' N,74o 43' 571'' E,12o 51' 428'' N,74o 43' 716'' E,265.95
16,2014-02-07 00:00:00,12o 48' 086'' N,74o 41' 299'' E,12o 52' 191'' N,74o 40' 218'' E,157.1
17,2014-02-20 00:00:00,13o 22' 389'' N,74o 35' 412'' E,13o 25' 389'' N,74o 35' 230'' E,243.35
18,2014-02-20 00:00:00,13o 25' 740'' N,74o 35' 840'' E,13o 21' 240'' N,74o 33' 700'' E,432.8

In [147]:
catch['Lat_start'] = catch['Lat_start'].str.replace(r'[oNS]',' ',regex=True)
catch['Long_start'] = catch['Long_start'].str.replace(r'[oEW]',' ',regex=True)
catch['Lat_end'] = catch['Lat_end'].str.replace(r'[oNS]',' ',regex=True)
catch['Long_end'] = catch['Long_end'].str.replace(r'[oEW]',' ',regex=True)
catch['Lat_start'] = catch['Lat_start'].str.replace(r"'"," ",regex=True)
catch['Long_start'] = catch['Long_start'].str.replace(r"'"," ",regex=True)
catch['Lat_end'] = catch['Lat_end'].str.replace(r"'"," ",regex=True)
catch['Long_end'] = catch['Long_end'].str.replace(r"'"," ",regex=True)

In [148]:
catch

,Date,Lat_start,Long_start,Lat_end,Long_end,Total
9,2014-10-01 00:00:00,13 15 235,74 28 608,13 16 235,74 28 523,79.65
10,2014-10-01 00:00:00,13 17 547,74 27 638,13 19 104,74 27 421,213.59
11,23/01/2014,12 51 571,74 43 571,12 51 428,74 43 716,413.95
12,23/01/2014,12 48 086,74 41 299,12 52 191,74 40 218,99.5
13,27/01/2014,13 22 389,74 35 412,13 25 389,74 35 230,186.1
14,27/01/2014,13 25 740,74 35 840,13 21 240,74 33 700,282.8
15,2014-02-07 00:00:00,12 51 571,74 43 571,12 51 428,74 43 716,265.95
16,2014-02-07 00:00:00,12 48 086,74 41 299,12 52 191,74 40 218,157.1
17,2014-02-20 00:00:00,13 22 389,74 35 412,13 25 389,74 35 230,243.35
18,2014-02-20 00:00:00,13 25 740,74 35 840,13 21 240,74 33 700,432.8

In [149]:
import convert

In [150]:
catch['Lat_start']=catch['Lat_start'].apply(convert.convert_coord_3)
catch['Long_start']=catch['Long_start'].apply(convert.convert_coord_3)
catch['Lat_end']=catch['Lat_end'].apply(convert.convert_coord_3)
catch['Long_end']=catch['Long_end'].apply(convert.convert_coord_3)

In [151]:
catch

                   Date  Lat_start  Long_start    Lat_end   Long_end   Total
9   2014-10-01 00:00:00  13.253917   74.476800  13.270583  74.475383   79.65
10  2014-10-01 00:00:00  13.292450   74.460633  13.318400  74.457017  213.59
11           23/01/2014  12.859517   74.726183  12.857133  74.728600  413.95
12           23/01/2014  12.801433   74.688317  12.869850  74.670300    99.5
13           27/01/2014  13.373150   74.590200  13.423150  74.587167   186.1
14           27/01/2014  13.429000   74.597333  13.354000  74.561667   282.8
15  2014-02-07 00:00:00  12.859517   74.726183  12.857133  74.728600  265.95
16  2014-02-07 00:00:00  12.801433   74.688317  12.869850  74.670300   157.1
17  2014-02-20 00:00:00  13.373150   74.590200  13.423150  74.587167  243.35
18  2014-02-20 00:00:00  13.429000   74.597333  13.354000  74.561667   432.8

In [152]:
catch.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 9 to 18
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Lat_start   10 non-null     float64
 2   Long_start  10 non-null     float64
 3   Lat_end     10 non-null     float64
 4   Long_end    10 non-null     float64
 5   Total       10 non-null     object
dtypes: float64(4), object(2)
memory usage: 560.0+ bytes

In [153]:
catch['Lat']= (catch['Lat_start'] + catch['Lat_end'])/2
catch['Long'] = (catch['Long_start'] + catch['Long_end'])/2

In [154]:
catch

,Date,Lat_start,Long_start,Lat_end,Long_end,Total,Lat,Long
9,2014-10-01 00:00:00,13.253917,74.476800,13.270583,74.475383,79.65,13.262250,74.476092
10,2014-10-01 00:00:00,13.292450,74.460633,13.318400,74.457017,213.59,13.305425,74.458825
11,23/01/2014,12.859517,74.726183,12.857133,74.728600,413.95,12.858325,74.727392
12,23/01/2014,12.801433,74.688317,12.869850,74.670300,99.5,12.835642,74.679308
13,27/01/2014,13.373150,74.590200,13.423150,74.587167,186.1,13.398150,74.588683
14,27/01/2014,13.429000,74.597333,13.354000,74.561667,282.8,13.391500,74.579500
15,2014-02-07 00:00:00,12.859517,74.726183,12.857133,74.728600,265.95,12.858325,74.727392
16,2014-02-07 00:00:00,12.801433,74.688317,12.869850,74.670300,157.1,12.835642,74.679308
17,2014-02-20 00:00:00,13.373150,74.590200,13.423150,74.587167,243.35,13.398150,74.588683
18,2014-02-20 00:00:00,13.429000,74.597333,13.354000,74.561667,432.8,13.391500,74.579500

In [155]:
catch.drop(columns=['Lat_start','Long_start','Lat_end','Long_end'],inplace=True)

In [156]:
catch

                   Date   Total        Lat       Long
9   2014-10-01 00:00:00   79.65  13.262250  74.476092
10  2014-10-01 00:00:00  213.59  13.305425  74.458825
11           23/01/2014  413.95  12.858325  74.727392
12           23/01/2014    99.5  12.835642  74.679308
13           27/01/2014   186.1  13.398150  74.588683
14           27/01/2014   282.8  13.391500  74.579500
15  2014-02-07 00:00:00  265.95  12.858325  74.727392
16  2014-02-07 00:00:00   157.1  12.835642  74.679308
17  2014-02-20 00:00:00  243.35  13.398150  74.588683
18  2014-02-20 00:00:00   432.8  13.391500  74.579500

In [157]:
catch['Date']=pd.to_datetime(catch['Date'])

In [158]:
catch

         Date   Total        Lat       Long
9  2014-10-01   79.65  13.262250  74.476092
10 2014-10-01  213.59  13.305425  74.458825
11 2014-01-23  413.95  12.858325  74.727392
12 2014-01-23    99.5  12.835642  74.679308
13 2014-01-27   186.1  13.398150  74.588683
14 2014-01-27   282.8  13.391500  74.579500
15 2014-02-07  265.95  12.858325  74.727392
16 2014-02-07   157.1  12.835642  74.679308
17 2014-02-20  243.35  13.398150  74.588683
18 2014-02-20   432.8  13.391500  74.579500

In [159]:
catch.to_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_karn.csv',index=False)