In [1]:
import numpy as np
import pandas as pd
import sheets
import convert

In [2]:
data=pd.ExcelFile(r'C:\Users\vodla\Downloads\Incois\09-WestBengal_SugataHazra_Data_2013-14.xlsx')

In [3]:
for i, sheet_name in enumerate(data.sheet_names, start=1):

    cleaned = sheets.sheets_split(
        data.parse(sheet_name)
    )
    if cleaned is not None:
        globals()[f'sheet_{i}'] = cleaned
        print(f"Sheet {i} cleaned and stored as sheet_{i}")
    else:
        print(f"Sheet {i} could not be cleaned.")

Sheet 1 could not be cleaned.
Sheet 2 cleaned and stored as sheet_2
Sheet 3 cleaned and stored as sheet_3
Sheet 4 cleaned and stored as sheet_4
Sheet 5 cleaned and stored as sheet_5
Sheet 6 cleaned and stored as sheet_6
Sheet 7 cleaned and stored as sheet_7
Sheet 8 cleaned and stored as sheet_8
Sheet 9 cleaned and stored as sheet_9
Sheet 10 could not be cleaned.

In [4]:
sheet_2

46,DATE,LAT,Long,HOUR OF FISHING,DEPTH(ft),HILSA Catch(kg),Total Catch(KG),CPUE(KG/H),NaN,NaN,NaN
0,29/6/2013,21 19 654,88 20 654,9,8,15,85,9.44,NaN,NaN,NaN
1,2013-01-07 00:00:00,21 17 544,88 15 544,7,15,40,90,12.86,NaN,NaN,NaN
2,2013-01-07 00:00:00,21 17 256,88 17 562,11,15,40,100,9.09,NaN,NaN,NaN
3,2013-02-07 00:00:00,21 21 250,88 12 456,6.2,14,20,50,8.06,NaN,NaN,NaN
4,2013-02-07 00:00:00,21 17 021,88 17 546,14,16,10,50,3.57,NaN,NaN,NaN
5,2013-03-07 00:00:00,21 17 654,88 16 561,8,15,5,25,3.13,NaN,NaN,NaN
6,2013-03-07 00:00:00,21 14 255,88 15 456,9,16,10,55,6.11,NaN,NaN,NaN
7,1931-04-07 00:00:00,21 15 456,88 15 412,11.3,16,5,30,2.65,NaN,NaN,NaN
8,2013-04-07 00:00:00,21 14 862,88 18 231,9.2,16,5,20,2.17,NaN,NaN,NaN
9,2013-11-07 00:00:00,21 20 398,88 16 523,7.4,14,25,55,7.43,NaN,NaN,NaN
10,2013-12-07 00:00:00,21 18 256,88 15 654,9,14,20,70,7.78,NaN,NaN,NaN
11,2013-12-07 00:00:00,21 16 600,88 18 458,10,15,30,80,8,NaN,NaN,NaN
12,15.07.13,21 16 982,88 07 560,7.3,12,30,45,6.16,NaN,NaN,NaN
13,16/07/13,21 20 568,88 13 654,4.4,14,20,20,4.55,NaN,NaN,NaN
14,16/07/13,21 24 236,88 15 681,13,12,30,40,3.08,NaN,NaN,NaN
15,17/07/13,21 23 562,88 13 459,9.2,12,20,25,2.72,NaN,NaN,NaN

In [5]:
wb2 = sheet_2[['DATE','LAT','Long','Total Catch(KG)']].copy()

In [6]:
wb2

46                 DATE        LAT       Long Total Catch(KG)
0             29/6/2013  21 19 654  88 20 654              85
1   2013-01-07 00:00:00  21 17 544  88 15 544              90
2   2013-01-07 00:00:00  21 17 256  88 17 562             100
3   2013-02-07 00:00:00  21 21 250  88 12 456              50
4   2013-02-07 00:00:00  21 17 021  88 17 546              50
5   2013-03-07 00:00:00  21 17 654  88 16 561              25
6   2013-03-07 00:00:00  21 14 255  88 15 456              55
7   1931-04-07 00:00:00  21 15 456  88 15 412              30
8   2013-04-07 00:00:00  21 14 862  88 18 231              20
9   2013-11-07 00:00:00  21 20 398  88 16 523              55
10  2013-12-07 00:00:00  21 18 256  88 15 654              70
11  2013-12-07 00:00:00  21 16 600  88 18 458              80
12             15.07.13  21 16 982  88 07 560              45
13             16/07/13  21 20 568  88 13 654              20
14             16/07/13  21 24 236  88 15 681              40
15             17/07/13  21 23 562  88 13 459              25

In [7]:
sheet_3

16,Date,Lat,Long,Hour of fishing,Depth (m),Hilsa Catch (kg),Hilsa CPUE (kg/h),NaN,NaN,NaN,NaN
0,28.07.13,21 06 39,88 19 21,7,15,240,34.29,NaN,NaN,NaN,NaN
1,28.07.13,21 18 41,88 17 47,5,12,50,10,NaN,NaN,NaN,NaN
2,29.07.13,21 19 15,88 21 53,6,12,40,6.67,NaN,NaN,NaN,NaN
3,30.07.13,21 25 56,88 15 23,6,12,100,16.67,NaN,NaN,NaN,NaN
4,30.07.13,21 25 56,88 11 32,4,10,40,10,NaN,NaN,NaN,NaN
5,30.07.13,21 21 36,88 10 47,4,12,10,2.5,NaN,NaN,NaN,NaN
6,31.07.13,21 23 39,88 13 25,7,10,30,4.29,NaN,NaN,NaN,NaN
7,01.08.13,21 25 34,88 19 48,4,9,30,7.5,NaN,NaN,NaN,NaN
8,01.08.13,21 14 56,88 15 41,7,14,30,4.29,NaN,NaN,NaN,NaN
9,02.08.13,21 12 33,88 14 34,8,12,50,6.25,NaN,NaN,NaN,NaN
10,03.08.13,21 10 51,88 11 37,10,13,10,1,NaN,NaN,NaN,NaN
11,04.08.13,21 05 42,88 11 41,7,16,40,5.71,NaN,NaN,NaN,NaN
12,04.08.13,21 13 52,88 25 47,8,14,140,17.5,NaN,NaN,NaN,NaN
13,05.08.13,21 20 45,88 16 34,6,16,200,33.33,NaN,NaN,NaN,NaN
14,05.08.13,21 22 31,88 15 22,7,15,40,5.71,NaN,NaN,NaN,NaN
15,06.08.13,21 20 24,88 07 29,9,12,50,5.56,NaN,NaN,NaN,NaN
16,06.08.13,21 10 34,87 58 45,9,17,60,6.67,NaN,NaN,NaN,NaN

In [8]:
sheet_3.columns

Index([             'Date',              'Lat ',              'Long',
         'Hour of fishing',         'Depth (m)',  'Hilsa Catch (kg)',
       'Hilsa CPUE (kg/h)',                 nan,                 nan,
                       nan,                 nan],
      dtype='object', name=16)

In [9]:
wb3 = sheet_3[['Date','Lat ','Long','Hilsa Catch (kg)']].copy()

In [10]:
sheet_4

34,Date,Lat,Long,Hour of fishing,Depth (m),Hilsa Catch (kg),Hilsa CPUE (kg/h),Total Catch (kg),Total CPUE (kg/h),NaN,NaN,NaN,NaN
0,1.09.13,21 23 502,88 15 548,6,11,10,1.67,13,2.17,NaN,NaN,NaN,NaN
1,1.09.13,21 10 214,89 13 105,6,48,100,16.67,380,63.33,NaN,NaN,NaN,NaN
2,2.09.13,21 06 502,89 14 297,7.5,67,50,6.67,305,40.67,NaN,NaN,NaN,NaN
3,2.09.13,20 53 943,89 17 405,9.5,135,200,21.05,230,24.21,NaN,NaN,NaN,NaN
4,2.09.13,20 56 496,89 11 359,10.5,105,15,1.43,23,2.19,NaN,NaN,NaN,NaN
5,3.09.13,20 53 889,89 14 359,6.5,125,20,3.08,47,7.23,NaN,NaN,NaN,NaN
6,9.09.13,21 09 037,88 46 897,6.3,18,5,0.79,56,8.89,NaN,NaN,NaN,NaN
7,10.09.13,21 15 717,88 57 150,7.2,14,10,1.39,62,8.61,NaN,NaN,NaN,NaN
8,10.09.13,21 07 462,89 06 055,6,33,30,5,34,5.67,NaN,NaN,NaN,NaN
9,11.09.13,21 17 958,89 00 586,8,14,40,5,71,8.88,NaN,NaN,NaN,NaN
10,11.09.13,21 21 235,88 54 525,7.1,16,20,2.82,23,3.24,NaN,NaN,NaN,NaN
11,12.09.13,21 16 653,88 50 740,8,15,40,5,45,5.63,NaN,NaN,NaN,NaN
12,12.09.13,21 16 326,88 50 108,7.5,15,16,2.13,20,2.67,NaN,NaN,NaN,NaN
13,13.09.13,21 09 090,88 44 823,13.4,17,300,22.39,505,37.69,NaN,NaN,NaN,NaN
14,14.09.13,21 13 329,88 46 225,7,14,15,2.14,67,9.57,NaN,NaN,NaN,NaN
15,14.09.13,21 09 605,88 35 635,10.8,16,50,4.63,52,4.81,NaN,NaN,NaN,NaN
16,15.09.13,21 02 252,88 18 705,9.2,17,15,1.63,20,2.17,NaN,NaN,NaN,NaN
17,16.09.13,20 57 905,88 17 925,4.4,40,2,0.45,27,6.14,NaN,NaN,NaN,NaN

In [11]:
wb4 = sheet_4[['Date','Lat ','Long','Total Catch (kg)']].copy()

In [12]:
wb4

34      Date        Lat         Long Total Catch (kg)
0    1.09.13   21 23 502   88 15 548               13
1    1.09.13   21 10 214   89 13 105              380
2    2.09.13   21 06 502   89 14 297              305
3    2.09.13   20 53 943   89 17 405              230
4    2.09.13   20 56 496   89 11 359               23
5    3.09.13   20 53 889   89 14 359               47
6    9.09.13   21 09 037   88 46 897               56
7   10.09.13   21 15 717  88 57 150                62
8   10.09.13   21 07 462   89 06 055               34
9   11.09.13   21 17 958   89 00 586               71
10  11.09.13   21 21 235   88 54 525               23
11  12.09.13   21 16 653   88 50 740               45
12  12.09.13   21 16 326   88 50 108               20
13  13.09.13   21 09 090   88 44 823              505
14  14.09.13   21 13 329   88 46 225               67
15  14.09.13   21 09 605   88 35 635               52
16  15.09.13   21 02 252   88 18 705               20
17  16.09.13   20 57 905   88 17 925               27

In [13]:
sheet_5

34,Date,Lat,Long,Hour of fishing,Depth (m),Hilsa catch (kg),Hilsa CPUE (kg/h),Total catch (kg),Total CPUE (kg/h)
0,26.09.13,21 22 41,88 02 84,9,12,40,4.44,43,4.78
1,26.09.13,21 18 26,88 05 36,10,10,70,7,73,7.3
2,26.09.13,21 16 33,88 05 39,11,14,70,6.36,77,7
3,27.09.13,21 13 53,88 03 36,12,14,40,3.33,42,3.5
4,27.09.13,21 14 26,88 04 44,11,14,15,1.36,17,1.55
5,28.09.13,21 16 26,88 16 42,10,12,25,2.5,27,2.7
6,28.09.13,21 16 23,88 06 36,8,12,15,1.88,17,2.13
7,01.10.13,21 15 26,88 09 26,7,10,70,10,72,10.29
8,02.10.13,21 15 26,88 09 13,9,14,50,5.56,52,5.78
9,02.10.13,21 10 23,88 27 24,8,18,40,5,42,5.25
10,03.10.13,21 18 28,88 20 56,17,16,68,4,88,5.18
11,04.10.13,21 22 23,88 20 26,17,10,47,2.76,51,3
12,07.10.13,21 04 26,88 23 26,5,26,10,2,18,3.6
13,08.10.13,21 10 23,88 20 12,3,14,10,3.33,16,5.33
14,08.10.13,21 06 23,88 18 26,10,14,22,2.2,85,8.5
15,09.10.13,21 35 23,88 20 15,13,18,12,0.92,41,3.15
16,10.10.13,21 03 56,88 17 25,16,28,6,0.38,132,8.25
17,16.10.13,21 02 23,88 23 56,8,18,50,6.25,132,16.5
18,17.10.13,21 06 12,88 21 26,7,30,25,3.57,59,8.43
19,18.10.13,21 03 23,88 23 26,8,18,10,1.25,30,3.75
20,18.10.13,20 54 56,88 20 21,7,60,7,1,57,8.14
21,19.10.13,21 09 23,88 20 15,12,13,20,1.67,77,6.42
22,19.10.13,20 56 02,88 22 33,8,42,109,13.63,119,14.88

In [14]:
wb5 = sheet_5[['Date','Lat','Long','Total catch (kg)']].copy()

In [15]:
wb5

34       Date        Lat      Long Total catch (kg)
0    26.09.13   21 22 41  88 02 84               43
1    26.09.13   21 18 26  88 05 36               73
2    26.09.13   21 16 33  88 05 39               77
3    27.09.13   21 13 53  88 03 36               42
4    27.09.13   21 14 26  88 04 44               17
5    28.09.13   21 16 26  88 16 42               27
6    28.09.13   21 16 23  88 06 36               17
7    01.10.13   21 15 26  88 09 26               72
8    02.10.13   21 15 26  88 09 13               52
9    02.10.13   21 10 23  88 27 24               42
10   03.10.13   21 18 28  88 20 56               88
11   04.10.13   21 22 23  88 20 26               51
12   07.10.13   21 04 26  88 23 26               18
13   08.10.13   21 10 23  88 20 12               16
14   08.10.13   21 06 23  88 18 26               85
15   09.10.13   21 35 23  88 20 15               41
16   10.10.13   21 03 56  88 17 25              132
17   16.10.13   21 02 23  88 23 56              132
18   17.10.13  21 06 12   88 21 26               59
19   18.10.13   21 03 23  88 23 26               30
20   18.10.13   20 54 56  88 20 21               57
21   19.10.13   21 09 23  88 20 15               77
22   19.10.13   20 56 02  88 22 33              119

In [16]:
sheet_6

36,DATE,LAT,Long,HOUR OF FISHING,DEPTH(m),HILSA Catch(kg),Total Catch (Kg),Hilsa CPUE,Total CPUE
0,28.10.13,21 15 48,88 16 32,4,10,30,35,7.5,8.75
1,29.10.13,21 16 26,88 17 45,15,14,25,65,1.67,4.33
2,30.10.13,21 09 20,88 19 45,6,15,60,110,10,18.33
3,30.10.13,21 09 23,88 19 56,12,15,100,120,8.33,10
4,31.10.13,21 10 03,88 20 44,8,15,20,30,2.5,3.75
5,31 10.13,21 09 53,88 19 22,11,15,20,40,1.82,3.64
6,01.11.13,21 02 22,88 17 36,9,20,40,100,4.44,11.11
7,01.11.13,21 00 20,88 21 30,7,20,10,120,1.43,17.14
8,02.11.13,21 05 26,88 18 26,8,15,5,35,0.63,4.38
9,03.11.13,20 54 18,88 17 57,5,28,45,60,9,12
10,04.11.13,20 88 45,87 57 48,10,70,80,80,8,8
11,06.11.13,20 51 45,88 17 56,7,50,200,320,28.57,45.71
12,07.11.13,20 54 40,88 18 36,9,50,200,440,22.22,48.89
13,07.11.13,21 00 25,88 20 49,10,34,20,140,2,14
14,08.11.13,20 57 08,88 20 12,6,15,10,440,1.67,73.33
15,08.11.13,21 08 35,88 19 32,6,15,20,50,3.33,8.33
16,08.11.13,21 03 37,88 21 75,9,15,30,40,3.33,4.44
17,10.11.13,20 58 26,88 35 45,10,32,40,160,4,16
18,11.11.13,20 55 30,88 35 26,17,44,5,90,0.29,5.29
19,12.11.13,21 11 30,88 20 42,8,15,20,50,2.5,6.25
20,12.11.13,21 12 23,88 18 26,8,15,20,240,2.5,30
21,13.11.13,21 09 03,88 17 39,7,16,10,110,1.43,15.71
22,13.11.13,20 48 47,88 19 22,10,74,300,360,30,36
23,14.11.13,20 46 58,88 19 46,15,80,300,320,20,21.33

In [17]:
wb6 = sheet_6[['DATE','LAT','Long','Total Catch (Kg)']].copy()

In [18]:
wb6

36       DATE       LAT      Long Total Catch (Kg)
0    28.10.13  21 15 48  88 16 32               35
1    29.10.13  21 16 26  88 17 45               65
2    30.10.13  21 09 20  88 19 45              110
3    30.10.13  21 09 23  88 19 56              120
4    31.10.13  21 10 03  88 20 44               30
5    31 10.13  21 09 53  88 19 22               40
6    01.11.13  21 02 22  88 17 36              100
7    01.11.13  21 00 20  88 21 30              120
8    02.11.13  21 05 26  88 18 26               35
9    03.11.13  20 54 18  88 17 57               60
10   04.11.13  20 88 45  87 57 48               80
11   06.11.13  20 51 45  88 17 56              320
12   07.11.13  20 54 40  88 18 36              440
13  07.11.13   21 00 25  88 20 49              140
14   08.11.13  20 57 08  88 20 12              440
15   08.11.13  21 08 35  88 19 32               50
16   08.11.13  21 03 37  88 21 75               40
17   10.11.13  20 58 26  88 35 45              160
18   11.11.13  20 55 30  88 35 26               90
19   12.11.13  21 11 30  88 20 42               50
20   12.11.13  21 12 23  88 18 26              240
21   13.11.13  21 09 03  88 17 39              110
22   13.11.13  20 48 47  88 19 22              360
23   14.11.13  20 46 58  88 19 46              320

In [19]:
sheet_7

21,Date,Lat,Long,Time(H),Depth(m),Total Catch(Kg),CPUE,NaN,NaN,NaN,NaN,NaN,NaN
0,26.11.13,21 05 40,88 18 56,5,15,10,2,NaN,NaN,NaN,NaN,NaN,NaN
1,27.11.13,21 02 45,88 21 35,11,18,25,2.27,NaN,NaN,NaN,NaN,NaN,NaN
2,28.11.13,21 30 41,88 15 41,9,20,9,1,NaN,NaN,NaN,NaN,NaN,NaN
3,29.11.13,21 07 50,88 14 56,11,18,100,9.09,NaN,NaN,NaN,NaN,NaN,NaN
4,30.11.13,21 31 45,88 15 29,8,21,15,1.88,NaN,NaN,NaN,NaN,NaN,NaN
5,01.12.13,21 05 35,88 21 41,6,20,8,1.33,NaN,NaN,NaN,NaN,NaN,NaN
6,02.12.13,21 00 31,88 20 29,8,21,19,2.38,NaN,NaN,NaN,NaN,NaN,NaN
7,03.12.13,21 01 35,88 20 51,8,19,11,1.38,NaN,NaN,NaN,NaN,NaN,NaN
8,04.12.13,21 05 41,88 19 35,5,15,11,2.2,NaN,NaN,NaN,NaN,NaN,NaN
9,05.12.13,20 59 51,88 19 24,8,21,33,4.13,NaN,NaN,NaN,NaN,NaN,NaN
10,06.12.13,20 35 49,88 20 42,9,21,6,0.67,NaN,NaN,NaN,NaN,NaN,NaN
11,07.12.13,21 02 25,88 22 31,6,16,20,3.33,NaN,NaN,NaN,NaN,NaN,NaN
12,08.12.13,21 03 52,88 22 51,6,14,15,2.5,NaN,NaN,NaN,NaN,NaN,NaN
13,10.12.13,21 09 51,87 54 11,5,13,20,4,NaN,NaN,NaN,NaN,NaN,NaN
14,12.12.13,21 05 46,87 59 34,4,17,30,7.5,NaN,NaN,NaN,NaN,NaN,NaN
15,13.12.13,21 03 54,88 04 51,5,17,35,7,NaN,NaN,NaN,NaN,NaN,NaN
16,14.12.13,21 02 45,88 16 21,7,22,5,0.71,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
wb7 = sheet_7[['Date','Lat','Long','Total Catch(Kg)']].copy()

In [21]:
wb7

21      Date       Lat      Long Total Catch(Kg)
0   26.11.13  21 05 40  88 18 56              10
1   27.11.13  21 02 45  88 21 35              25
2   28.11.13  21 30 41  88 15 41               9
3   29.11.13  21 07 50  88 14 56             100
4   30.11.13  21 31 45  88 15 29              15
5   01.12.13  21 05 35  88 21 41               8
6   02.12.13  21 00 31  88 20 29              19
7   03.12.13  21 01 35  88 20 51              11
8   04.12.13  21 05 41  88 19 35              11
9   05.12.13  20 59 51  88 19 24              33
10  06.12.13  20 35 49  88 20 42               6
11  07.12.13  21 02 25  88 22 31              20
12  08.12.13  21 03 52  88 22 51              15
13  10.12.13  21 09 51  87 54 11              20
14  12.12.13  21 05 46  87 59 34              30
15  13.12.13  21 03 54  88 04 51              35
16  14.12.13  21 02 45  88 16 21               5

In [22]:
sheet_8

28,Date,Lat,Long,Hour of fishing,Depth (m),Total catch,CPUE,Name of fish,NaN,NaN,NaN,NaN,NaN
0,01.01.14,21 06 10,88 20 36,7,20,15,2.14,"Pomfret, Hilsa",NaN,NaN,NaN,NaN,NaN
1,NaN,20 58 45,88 22 28,8,20,35,4.38,"Phasa,",NaN,NaN,NaN,NaN,NaN
2,02.01.14,21 03 14,88 17 07,8,16,20,2.5,pomfret,NaN,NaN,NaN,NaN,NaN
3,NaN,20 55 08,88 22 20,8,34,25,3.13,"Silver Pomfret, Black pomfret",NaN,NaN,NaN,NaN,NaN
4,03.01.14,21 10 24,88 16 42,7,16,40,5.71,Pomfret,NaN,NaN,NaN,NaN,NaN
5,NaN,20 55 34,88 19 50,4,26,25,6.25,Pomfret,NaN,NaN,NaN,NaN,NaN
6,04.01.14,21 05 20,88 20 08,7,16,30,4.29,"Hilsa, Sardine",NaN,NaN,NaN,NaN,NaN
7,05.01.14,21 01 04,88 08 04,11,16,45,4.09,Pomfret,NaN,NaN,NaN,NaN,NaN
8,NaN,20 57 23,88 10 14,30,32,75,2.5,"Hilsa , Phasa,",NaN,NaN,NaN,NaN,NaN
9,06.01.14,21 02 20,88 09 77,11,22,30,2.73,"Hilsa , Pomfret",NaN,NaN,NaN,NaN,NaN
10,07.01.14,20 56 23,88 20 29,3,20,70,23.33,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
11,08.01.14,20 57 38,88 21 22,1,18,240,240,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
12,10.01.14,20 59 14,88 18 23,3,15,15,5,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
13,11.01.14,21 06 32,88 16 35,7,12,15,2.14,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
14,12.01.14,20 55 16,88 21 23,3,22,10,3.33,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
15,13.01.14,21 07 59,88 22 13,4,12,17,4.25,Protonibea sp.,NaN,NaN,NaN,NaN,NaN
16,14.01.14,21 03 35,88 16 29,6,16,80,13.33,"Bombay duck, Anchovy",NaN,NaN,NaN,NaN,NaN
17,15.01.14,21 03 41,88 16 21,5,18,70,14,Pomfret,NaN,NaN,NaN,NaN,NaN
18,16.01.14,21 03 56,88 20 42,7,18,35,5,Pomfret,NaN,NaN,NaN,NaN,NaN
19,17.01.14,21 04 25,88 16 31,9,18,45,5,"Pomfret, Hilsa",NaN,NaN,NaN,NaN,NaN

In [23]:
wb8 = sheet_8[['Date','Lat ','Long ','Total catch']].copy()

In [24]:
wb8['Date'] = wb8['Date'].ffill()

In [25]:
wb8

28      Date      Lat       Long  Total catch
0   01.01.14  21 06 10   88 20 36          15
1   01.01.14  20 58 45   88 22 28          35
2   02.01.14  21 03 14   88 17 07          20
3   02.01.14  20 55 08  88 22 20           25
4   03.01.14  21 10 24   88 16 42          40
5   03.01.14  20 55 34   88 19 50          25
6   04.01.14  21 05 20   88 20 08          30
7   05.01.14  21 01 04   88 08 04          45
8   05.01.14  20 57 23   88 10 14          75
9   06.01.14  21 02 20   88 09 77          30
10  07.01.14  20 56 23   88 20 29          70
11  08.01.14  20 57 38   88 21 22         240
12  10.01.14  20 59 14   88 18 23          15
13  11.01.14  21 06 32   88 16 35          15
14  12.01.14  20 55 16   88 21 23          10
15  13.01.14  21 07 59   88 22 13          17
16  14.01.14  21 03 35   88 16 29          80
17  15.01.14  21 03 41   88 16 21          70
18  16.01.14  21 03 56  88 20 42           35
19  17.01.14  21 04 25   88 16 31          45

In [26]:
sheet_9

34,DATE,LAT,Long,HOUR OF FISHING,DEPTH(m),Total Catch,Total CPUE,NaN,NaN
0,26.01.14,21 03 26,88 19 50,8,16,25,3.13,NaN,NaN
1,27.01.14,21 03 20,21 02 34,6,16,30,5,NaN,NaN
2,28.01.14,21 00 28,88 21 45,10,18,30,3,NaN,NaN
3,29.01.14,20 58 25,88 19 30,8,22,25,3.13,NaN,NaN
4,30.01.14,21 06 52,88 20 35,11,15,30,2.73,NaN,NaN
5,31.01.14,21 05 10,88 21 25,8,16,35,4.38,NaN,NaN
6,01.02.14,21 06 23,88 17 42,5,16,26,5.2,NaN,NaN
7,02.02.14,21 04 48,88 21 31,11,15,50,4.55,NaN,NaN
8,03.02.14,21 07 23,88 21 02,8,16,20,2.5,NaN,NaN
9,04.02.14,21 03 08,88 16 25,6,16,15,2.5,NaN,NaN
10,10.02.14,21 08 50,88 15 35,11,16,213,19.36,NaN,NaN
11,11.02.14,21 06 22,88 16 12,16,18,358,22.38,NaN,NaN
12,12.02.14,21 05 46,88 05 39,13,18,68,5.23,NaN,NaN
13,13.02.14,21 03 56,88 05 54,20,17,225,11.25,NaN,NaN
14,14.02.14,21 07 20,88 03 21,18,22,435,24.17,NaN,NaN
15,15.02.14,21 03 12,88 15 30,11,22,25,2.27,NaN,NaN
16,16.02.14,21 00 30,88 22 52,11,40,30,2.73,NaN,NaN

In [27]:
wb9 = sheet_9[['DATE','LAT','Long','Total Catch']].copy()

In [28]:
wb9

34      DATE       LAT      Long Total Catch
0   26.01.14  21 03 26  88 19 50          25
1   27.01.14  21 03 20  21 02 34          30
2   28.01.14  21 00 28  88 21 45          30
3   29.01.14  20 58 25  88 19 30          25
4   30.01.14  21 06 52  88 20 35          30
5   31.01.14  21 05 10  88 21 25          35
6   01.02.14  21 06 23  88 17 42          26
7   02.02.14  21 04 48  88 21 31          50
8   03.02.14  21 07 23  88 21 02          20
9   04.02.14  21 03 08  88 16 25          15
10  10.02.14  21 08 50  88 15 35         213
11  11.02.14  21 06 22  88 16 12         358
12  12.02.14  21 05 46  88 05 39          68
13  13.02.14  21 03 56  88 05 54         225
14  14.02.14  21 07 20  88 03 21         435
15  15.02.14  21 03 12  88 15 30          25
16  16.02.14  21 00 30  88 22 52          30

In [29]:
wb2.columns = ['Date','Latitude','Longitude','Total Catch']
wb3.columns = ['Date','Latitude','Longitude','Total Catch']
wb4.columns = ['Date','Latitude','Longitude','Total Catch']
wb5.columns = ['Date','Latitude','Longitude','Total Catch']
wb6.columns = ['Date','Latitude','Longitude','Total Catch']
wb7.columns = ['Date','Latitude','Longitude','Total Catch']
wb8.columns = ['Date','Latitude','Longitude','Total Catch']
wb9.columns = ['Date','Latitude','Longitude','Total Catch']

In [30]:
wb_merged = pd.concat([wb2, wb3, wb4, wb5, wb6, wb7, wb8, wb9], ignore_index=True)

In [31]:
wb_merged

                    Date   Latitude  Longitude Total Catch
0              29/6/2013  21 19 654  88 20 654          85
1    2013-01-07 00:00:00  21 17 544  88 15 544          90
2    2013-01-07 00:00:00  21 17 256  88 17 562         100
3    2013-02-07 00:00:00  21 21 250  88 12 456          50
4    2013-02-07 00:00:00  21 17 021  88 17 546          50
..                   ...        ...        ...         ...
147             12.02.14   21 05 46   88 05 39          68
148             13.02.14   21 03 56   88 05 54         225
149             14.02.14   21 07 20   88 03 21         435
150             15.02.14   21 03 12   88 15 30          25
151             16.02.14   21 00 30   88 22 52          30

[152 rows x 4 columns]

In [32]:
wb_merged['Date'] = wb_merged['Date'].astype(str).str.replace('.', '-', regex=False).str.replace('/', '-', regex=False)

In [33]:
wb_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         152 non-null    str
 1   Latitude     152 non-null    object
 2   Longitude    152 non-null    object
 3   Total Catch  152 non-null    object
dtypes: object(3), str(1)
memory usage: 4.9+ KB

In [34]:
wb_merged['Date'] = pd.to_datetime(wb_merged['Date'], format='mixed', errors='coerce')

In [35]:
wb_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         152 non-null    datetime64[us]
 1   Latitude     152 non-null    object
 2   Longitude    152 non-null    object
 3   Total Catch  152 non-null    object
dtypes: datetime64[us](1), object(3)
memory usage: 4.9+ KB

In [36]:
wb_merged

          Date   Latitude  Longitude Total Catch
0   2013-06-29  21 19 654  88 20 654          85
1   2013-01-07  21 17 544  88 15 544          90
2   2013-01-07  21 17 256  88 17 562         100
3   2013-02-07  21 21 250  88 12 456          50
4   2013-02-07  21 17 021  88 17 546          50
..         ...        ...        ...         ...
147 2014-12-02   21 05 46   88 05 39          68
148 2014-02-13   21 03 56   88 05 54         225
149 2014-02-14   21 07 20   88 03 21         435
150 2014-02-15   21 03 12   88 15 30          25
151 2014-02-16   21 00 30   88 22 52          30

[152 rows x 4 columns]

In [37]:
wb_merged[wb_merged.duplicated(keep=False)]

Empty DataFrame
Columns: [Date, Latitude, Longitude, Total Catch]
Index: []

In [38]:
import convert
import importlib
importlib.reload(convert)

In [39]:
wb_merged['Latitude'] = wb_merged['Latitude'].apply(convert.convert_coord_3)

In [40]:
wb_merged['Longitude'] = wb_merged['Longitude'].apply(convert.convert_coord_3)

In [41]:
wb_merged

          Date   Latitude  Longitude Total Catch
0   2013-06-29  21.327567  88.344233          85
1   2013-01-07  21.292400  88.259067          90
2   2013-01-07  21.287600  88.292700         100
3   2013-02-07  21.354167  88.207600          50
4   2013-02-07  21.283683  88.292433          50
..         ...        ...        ...         ...
147 2014-12-02  21.084100  88.083983          68
148 2014-02-13  21.050933  88.084233         225
149 2014-02-14  21.117000  88.050350         435
150 2014-02-15  21.050200  88.250500          25
151 2014-02-16  21.000500  88.367533          30

[152 rows x 4 columns]

In [42]:
wb_merged['Latitude']=wb_merged['Latitude'].astype(float).round(4)
wb_merged['Longitude']=wb_merged['Longitude'].astype(float).round(4)

In [43]:
wb_merged

          Date  Latitude  Longitude Total Catch
0   2013-06-29   21.3276    88.3442          85
1   2013-01-07   21.2924    88.2591          90
2   2013-01-07   21.2876    88.2927         100
3   2013-02-07   21.3542    88.2076          50
4   2013-02-07   21.2837    88.2924          50
..         ...       ...        ...         ...
147 2014-12-02   21.0841    88.0840          68
148 2014-02-13   21.0509    88.0842         225
149 2014-02-14   21.1170    88.0504         435
150 2014-02-15   21.0502    88.2505          25
151 2014-02-16   21.0005    88.3675          30

[152 rows x 4 columns]

In [44]:
wb_merged[wb_merged.duplicated(subset=['Latitude','Longitude'], keep=False)]

Empty DataFrame
Columns: [Date, Latitude, Longitude, Total Catch]
Index: []

In [45]:
wb_merged[wb_merged['Date'].isnull()]

Empty DataFrame
Columns: [Date, Latitude, Longitude, Total Catch]
Index: []

In [46]:
wb_merged['Total Catch']=pd.to_numeric(wb_merged['Total Catch'], errors='coerce')

In [47]:
wb_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         152 non-null    datetime64[us]
 1   Latitude     152 non-null    float64
 2   Longitude    152 non-null    float64
 3   Total Catch  152 non-null    int64
dtypes: datetime64[us](1), float64(2), int64(1)
memory usage: 4.9 KB

In [48]:
wb_merged.to_csv(r'C:\Users\vodla\Downloads\Incois\Cleaned_wb.csv', index=False)